name: publish package on pypi

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: snok/install-poetry@v1.1.1
      - name: Publish to test-pypi
        run: |
          poetry config repositories.test https://test.pypi.org/legacy/
          poetry config pypi-token.test ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish --build --no-interaction --repository test --dry-run
      - name: Publish to pypi
        run: |
          poetry config repositories.pypi https://upload.pypi.org/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction --repository pypi --dry-run
